actions:
  greet:
    type: shell
    cmd: "echo Hello {{ input.name }} && echo 'OUTPUT: {\"greeting\": \"Hello {{ input.name }}\"}'"
    input:
      name: { type: string, required: true }

  greet-with-warning:
    type: shell
    cmd: "echo Hello {{ input.name }} && echo 'this is a warning' >&2 && echo 'OUTPUT: {\"greeting\": \"Hello {{ input.name }}\"}'"
    input:
      name: { type: string, required: true }

  shout:
    type: shell
    cmd: "echo {{ input.message }} | tr '[:lower:]' '[:upper:]'"
    input:
      message: { type: string, required: true }

tasks:
  hello-world:
    mode: distributed
    input:
      name: { type: string, default: "World" }
    flow:
      say-hello:
        action: greet
        input:
          name: "{{ input.name }}"
      shout-it:
        action: shout
        depends_on: [say-hello]
        input:
          message: "{{ say_hello.output.greeting }}"

  hello-with-warning:
    mode: distributed
    input:
      name: { type: string, default: "World" }
    flow:
      warn-hello:
        action: greet-with-warning
        input:
          name: "{{ input.name }}"

triggers:
  hello-every-10min:
    type: scheduler
    cron: "0 */10 * * * *"
    task: hello-world
    input:
      name: "Scheduler"
    enabled: true
